import {chapters,words,kanaRows,katakana} from './data.js';
import {initial,restore,start,answer,commit} from './engine.js';
const root=document.querySelector('#app');
const KEY=new URLSearchParams(location.search).has('test')?'nihongo-odyssey-test-v1':'nihongo-odyssey-v1';
let state=read(),session=null,learnIndex=0,view='map',kanaType='hira',roman=true,kanaQuiz=null;
function read(){try{return restore(localStorage.getItem(KEY));}catch{return initial();}}
function save(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;score();return true;}catch{notice('目前無法儲存進度，請確認瀏覽器允許網站儲存資料。');return false;}}
function notice(message){document.querySelector('#notice').textContent=message;clearTimeout(notice.timer);notice.timer=setTimeout(()=>document.querySelector('#notice').textContent='',6500);}
function score(){document.querySelector('#score').textContent=`${state.completed*5} / 100 詞 · ${state.completed*50} XP`;}
function stopVoice(){globalThis.speechSynthesis?.cancel();}
function speak(text,slow=false){if(!globalThis.speechSynthesis){notice('這個瀏覽器不支援朗讀，請參考卡片上的假名。');return;}const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('ja'));if(!voice){notice('裝置尚無可用的日語聲音，請先在系統安裝日語語音。仍可使用文字練習。');return;}stopVoice();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.voice=voice;u.rate=slow?.65:.85;u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))notice('朗讀未成功，請重試或檢查裝置語音設定。');};speechSynthesis.speak(u);}
const audio=(text)=>`<button data-speak="${text}">聽讀音</button> <button data-slow="${text}">慢速</button>`;
const landscape=`<svg class="landscape" viewBox="0 0 540 365" role="img" aria-label="山巒、櫻花與小鎮車站的旅行插畫"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#e8eedd"/><stop offset="1" stop-color="#f8f5ec"/></linearGradient></defs><rect x="12" y="15" width="515" height="325" rx="160" fill="url(#sky)"/><circle cx="396" cy="87" r="39" fill="#d99c77" opacity=".7"/><path d="M12 252 122 84 240 248 343 124 525 268Z" fill="#b4c6b0"/><path d="m73 161 49-77 54 77-35-13-18 12-20-15Z" fill="#fffdf3"/><path d="M12 277Q124 181 216 247T527 244V320H12Z" fill="#7e9d87"/><path d="M12 313Q146 247 288 310T527 293V339H12Z" fill="#c4ceb0"/><path d="m248 350 65-72 24 0 95 72" fill="#e1c7a0"/><path d="M188 231h171v75H188z" fill="#efe2c3"/><path d="m169 235 105-52 106 52z" fill="#416359"/><path d="M252 249h40v57h-40z" fill="#576f63"/><path d="M201 251h32v25h-32zm107 0h34v25h-34z" fill="#9cbab1"/><rect x="246" y="208" width="56" height="20" rx="2" fill="#f6ecd4"/><text x="274" y="222" text-anchor="middle" fill="#416359" font-size="11">旅の駅</text><path d="M90 306 97 201 69 166m28 52 38-56" fill="none" stroke="#777965" stroke-width="7"/><g fill="#e4b7aa" opacity=".9"><circle cx="66" cy="164" r="29"/><circle cx="100" cy="150" r="35"/><circle cx="136" cy="162" r="28"/><circle cx="91" cy="185" r="26"/></g><path d="M411 306v-44m-15 5h31" stroke="#5a7764" stroke-width="6"/><text x="441" y="331" font-size="11" fill="#5a7764">一歩ずつ。</text></svg>`;
function navigate(next){if(session && !session.done && !confirm('離開會重新開始這次小任務；已完成的任務會保留。要離開嗎？'))return;stopVoice();session=null;kanaQuiz=null;state=read();view=next;render();}
function render(){score();if(view==='map')map();else if(view==='kana')kana();else bag();}
function map(){const c=chapters[Math.min(9,Math.floor(state.completed/2))];root.innerHTML=`<section class="hero"><div><div class="eyebrow">一段旅程，從一句日語開始</div><h1>把日語，<br>變成沿途的風景。</h1><p>穿過小鎮車站，走進食堂與商店街。<br>一次認識五個詞，把每一天的小小進步放進行囊。</p><div class="actions"><button class="primary" id="continue">${state.completed===20?'全旅程完成 · 複習行囊':state.completed===0?'啟程 · 從第一站開始':`繼續旅行 · ${c.place}`}</button><button data-nav="kana">從五十音暖身</button></div></div>${landscape}</section><div class="section-head"><h2>你的十站旅行</h2><small>10 個場景 · 100 個入門詞<br>每站兩個五詞小任務</small></div><section class="map" aria-label="旅行關卡">${chapters.map((c,i)=>{const done=state.completed>=(i+1)*2,active=Math.floor(state.completed/2)===i,unlocked=i*2<=state.completed;return `<button class="stop ${done?'done':active?'active':''}" data-chapter="${i}" ${unlocked?'':'disabled'}><span class="num">${String(i+1).padStart(2,'0')}</span><strong>${c.place}</strong><small>${c.title}</small><span class="stamp">${done?'✓ 已收集旅程印章':active?`現在這裡 · ${state.completed%2}/2 任務`:'尚未抵達'}</span></button>`;}).join('')}</section><div class="section-head"><p class="muted">已會五十音？直接啟程即可。每個詞都附假名與例句。</p><button id="review" ${state.completed?'':'disabled'}>複習已學詞</button></div>`;document.querySelector('#continue').onclick=()=>begin(state.completed===20);document.querySelector('#review').onclick=()=>begin(true);root.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.chapter)*2<state.completed-1){view='bag';bag();}else begin(false);});}
function begin(review=false){state=read();session=start(state,review);learnIndex=0;stopVoice();if(!session.queue.length){notice('先完成一個旅行任務，再回來複習。');return;}if(session.fresh.length)learn();else question();}
function shell(html){root.innerHTML=`<section class="panel">${html}</section>`;window.scrollTo({top:0,behavior:'instant'});}
function learn(){const w=session.fresh[learnIndex],c=chapters[Math.floor(session.quest/2)];shell(`<div class="eyebrow">第 ${c.id} 站 · ${c.place} · 任務 ${session.quest%2+1}/2</div><h1>${c.title}</h1><p class="muted">${c.story}</p><div class="progress"><span style="width:${(learnIndex+1)*20}%"></span></div><small>認識新詞 ${learnIndex+1} / 5</small><div class="card"><div lang="ja" class="word">${w.word}</div><div lang="ja" class="reading">${w.kana}</div><div class="meaning">${w.meaning}</div><div class="actions" style="justify-content:center">${audio(w.kana)}</div><div class="example"><p lang="ja">${w.example}</p><p class="muted">${w.translation}</p><button data-speak="${w.example}">聽例句</button></div><button class="primary" id="learn-next">${learnIndex===4?'開始練習':'下一個詞'}</button></div>`);document.querySelector('#learn-next').onclick=()=>{stopVoice();if(++learnIndex<5)learn();else question();};}
function question(){const q=session.queue[0];if(!q){finish();return;}const w=words.find(x=>x.id===q.id);const choices=[w.meaning,...[...new Set(words.filter(x=>x.meaning!==w.meaning).map(x=>x.meaning))].sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);shell(`<div class="eyebrow">${q.review?'回顧沿途的詞':'旅途練習'} · 還有 ${session.queue.length} 題</div><h1>${q.mode==='meaning'?'這個詞是什麼意思？':'試著寫出它的假名'}</h1><p class="muted">${q.mode==='meaning'?'讀一讀，再選出意思。':'可用平假名或片假名作答；不接受羅馬拼音。'}</p><div class="card"><div class="word" lang="ja">${q.mode==='reading'?w.meaning:w.word}</div>${q.mode==='meaning'?`<p class="reading" lang="ja">${w.kana}</p><div class="choices">${choices.map(c=>`<button data-answer="${c}">${c}</button>`).join('')}</div>`:`<form id="reading-form"><label for="reading">日文假名</label><input id="reading" type="text" autocomplete="off" autocapitalize="off" spellcheck="false" lang="ja" required><div class="actions"><button class="primary" type="submit">確認答案</button><button type="button" id="hint">需要提示</button><button type="button" data-speak="${w.kana}">聽提示</button></div><p id="hint-text" class="muted"></p></form>`}<div id="feedback" class="feedback" role="status"></div><button class="primary" id="next" hidden>繼續</button></div>`);root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>submit(b.dataset.answer));const form=document.querySelector('#reading-form');if(form){form.onsubmit=e=>{e.preventDefault();submit(document.querySelector('#reading').value);};document.querySelector('#hint').onclick=()=>document.querySelector('#hint-text').textContent=`跟著讀一次：${w.kana}`;}document.querySelector('#next').onclick=()=>{stopVoice();session.done?finish():question();};}
function submit(value){const result=answer(session,value);if(!result)return;root.querySelectorAll('.choices button,form button,form input').forEach(b=>b.disabled=true);const feedback=document.querySelector('#feedback');feedback.className=`feedback ${result.ok?'':'wrong'}`;feedback.textContent=result.ok?'答對了！再往前走一點。':`這題的答案是「${result.expected}」。稍後再試一次。`;document.querySelector('#next').hidden=false;document.querySelector('#next').focus();}
function finish(){const latest=read();const saved=save(commit(latest,session));shell(`<div class="eyebrow">${saved?'旅程已保存在這個瀏覽器':'儲存未成功，請保留本頁'}</div><div class="completed">${session.fresh.length?'印':'✓'}</div><h1>${session.fresh.length?'又走過了一小段路。':'熟悉的詞，又見面了。'}</h1><p>這次完成 ${session.fresh.length?5:session.reviewed.length} 個詞的${session.fresh.length?'學習':'複習'}，重試 ${session.retries} 次。<br>答錯是練習的一部分，願意再試就值得記下。</p><p class="muted">${state.completed===20?'十站旅行完成！可以隨時回行囊複習。':'下一次打開，會從這裡接著走。'}</p><div class="actions"><button class="primary" id="back">回旅行地圖</button><button id="again">${saved?'再走一段':'重試儲存'}</button></div>`);document.querySelector('#back').onclick=()=>navigate('map');document.querySelector('#again').onclick=()=>saved?begin(state.completed===20):finish();}
function kana(){shell(`<div class="eyebrow">出發前的小練習</div><h1>先認識日語的聲音。</h1><p>平假名常用來標示讀音，片假名常見於外來語。按一格聽發音；羅馬拼音只是入門輔助，熟悉後可以隱藏。</p><div class="tabs"><button id="hira" class="${kanaType==='hira'?'selected':''}">平假名</button><button id="kata" class="${kanaType==='kata'?'selected':''}">片假名</button><button id="roman">${roman?'隱藏':'顯示'}拼音</button></div><div class="kana-grid">${kanaRows.map(([row,rom])=>[...row].map((k,i)=>k==='　'?'<span class="empty"></span>':`<button data-speak="${kanaType==='hira'?k:katakana(k)}" aria-label="${kanaType==='hira'?k:katakana(k)}，${rom.split(' ')[i]}"><span lang="ja">${kanaType==='hira'?k:katakana(k)}</span>${roman?`<small>${rom.split(' ')[i]}</small>`:''}</button>`).join('')).join('')}</div><p class="tip">小提醒：し＝shi、ち＝chi、つ＝tsu、ふ＝fu。助詞「は」常讀 wa，「へ」讀 e，「を」讀 o。<br>小小的「っ」讓下一個子音停頓一下：きっぷ（車票）。<br>「きゃ／きゅ／きょ」要合成一拍；片假名「ー」拉長前面的母音，例如コーヒー（咖啡）。<br>母音長短會影響意思：おばさん（阿姨）與おばあさん（奶奶）。「ん」是獨立一拍。</p><div class="actions"><button class="primary" id="kana-practice">練五題清音辨讀</button><button data-nav="map">我想直接開始旅行</button></div><p class="muted">${state.kanaDone?'✓ 已完成一次清音暖身；仍可再次練習。':'暖身可自由跳過，不影響旅行關卡。'}</p>`);document.querySelector('#hira').onclick=()=>{kanaType='hira';kana();};document.querySelector('#kata').onclick=()=>{kanaType='kata';kana();};document.querySelector('#roman').onclick=()=>{roman=!roman;kana();};document.querySelector('#kana-practice').onclick=()=>{kanaQuiz={index:0,items:[['あ','a'],['し','shi'],['つ','tsu'],['ね','ne'],['ん','n']]};kanaQuestion();};}
function kanaQuestion(){if(kanaQuiz.index===5){const current=read();current.kanaDone=true;save(current);shell('<h1>五題暖身完成。</h1><p>準備好就踏出第一步；想多練習，也能隨時回來。</p><button class="primary" data-nav="map">前往旅行地圖</button>');return;}const [k,rom]=kanaQuiz.items[kanaQuiz.index];shell(`<div class="eyebrow">五十音暖身 ${kanaQuiz.index+1}/5</div><h1>這個假名怎麼讀？</h1><div class="word" lang="ja">${kanaType==='hira'?k:katakana(k)}</div>${audio(k)}<div class="choices">${[...new Set([rom,'ka','mi','yo'])].sort(()=>Math.random()-.5).map(v=>`<button data-rom="${v}">${v}</button>`).join('')}</div><p class="feedback" id="kana-feedback" role="status"></p><button id="kana-next" hidden>下一題</button>`);root.querySelectorAll('[data-rom]').forEach(b=>b.onclick=()=>{const ok=b.dataset.rom===rom;document.querySelector('#kana-feedback').textContent=ok?'答對了！':`讀作 ${rom}，聽一次，再選看看。`;if(ok){root.querySelectorAll('[data-rom]').forEach(x=>x.disabled=true);document.querySelector('#kana-next').hidden=false;}});document.querySelector('#kana-next').onclick=()=>{kanaQuiz.index++;kanaQuestion();};}
function bag(){const learned=words.slice(0,state.completed*5);root.innerHTML=`<div class="section-head"><div><div class="eyebrow">沿途收集的日語</div><h1>單字行囊</h1><p class="muted">${learned.length} 個已學詞。學過與熟練不同，記得常回來相見。</p></div><button id="bag-review" ${learned.length?'':'disabled'}>開始複習</button></div>${learned.length?`<div class="bag">${learned.map(w=>`<article><h3 lang="ja">${w.word}</h3><div lang="ja">${w.kana}</div><p>${w.meaning}</p><p lang="ja">${w.example}</p><p class="muted">${w.translation}</p>${audio(w.kana)}</article>`).join('')}</div>`:'<section class="panel"><h2>行囊還是空的。</h2><p>完成第一個五詞任務，就能把它們帶在身邊。</p><button class="primary" data-nav="map">回地圖啟程</button></section>'}`;document.querySelector('#bag-review').onclick=()=>begin(true);}
document.addEventListener('click',e=>{const b=e.target.closest('button,a.brand');if(!b)return;if(b.matches('a.brand')){e.preventDefault();navigate('map');}else if(b.dataset.nav)navigate(b.dataset.nav);else if(b.dataset.speak)speak(b.dataset.speak);else if(b.dataset.slow)speak(b.dataset.slow,true);});
document.querySelector('#export').onclick=()=>{const blob=new Blob([JSON.stringify(read(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nihongo-odyssey-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notice('旅程備份已下載。此版尚未提供匯入功能。');};
window.addEventListener('storage',e=>{if(e.key===KEY){state=read();score();if(!session)render();}});
window.addEventListener('pagehide',stopVoice);
render();
