import {installChoiceKeyboard,choiceHint} from './choice-keyboard.js';
import {roles,regions} from './story.js';
import {lessons,commonGlossary} from './lessons.js';
import {words,byId,levels,chapters,counts} from './curriculum.js';
import {initial,restore,currentChapter,choose,chooseEntryLevel,chapterProgress,learnedIds,statsSummary,start,answer,commit,markHint,markFallback,startAssessment,answerAssessment,commitAssessment,serialize,saveSessionEvidence} from './engine.js';
import {mountKana} from './kana.js';
import {speak,stopVoice,japaneseVoice} from './voice.js';
import {readingCue,distractorPool} from './question-helpers.js';

const $=selector=>document.querySelector(selector),root=$('#app');
const test=new URLSearchParams(location.search).has('test');
const KEY=test?'nihongo-odyssey-test-v3':'nihongo-odyssey-v3';
const LEGACY=test?'nihongo-odyssey-test-v2':'nihongo-odyssey-v2';
let storageProblem=false,state=read(),view='map',selectedLevel=state.entryLevel,session=null,assessment=null,learnIndex=0,activeEpisode=null;
let screenToken=0;
let searchTerm='',dictionaryLevel='all',page=0,onlyLearned=false,furigana=true,glossLookup=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{const raw=localStorage.getItem(KEY);if(raw)return restore(raw,{strict:true});const old=localStorage.getItem(LEGACY);return old?restore(old,{strict:true}):initial();}catch{storageProblem=true;return initial();}}
function notify(message){$('#notice').textContent=message;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').textContent='',9000);}
function write(next){if(storageProblem){notify('現有存檔無法讀取，已暫停覆寫。請先到設定下載原始備份，再匯入有效備份。');return false;}try{localStorage.setItem(KEY,serialize(next));state=next;status();return true;}catch{notify('無法儲存進度，請檢查瀏覽器是否允許網站資料。');return false;}}
function mutate(fn){const run=()=>{state=read();return write(fn(state));};return navigator.locks?navigator.locks.request(KEY,run):Promise.resolve(run());}
async function persistEvidence(active=assessment??session){if(!active)return true;try{return await mutate(s=>saveSessionEvidence(s,active));}catch(e){notify(e.message);return false;}}
function status(){const s=statsSummary(state);$('#status').textContent=`${s.completed.toLocaleString()} 詞 · ${s.chaptersCleared}/25 章`;}
function roleArt(id,extra=''){const index=roles.findIndex(r=>r.id===id);if(index<0)return fox();return `<div class="role-art ${extra}" role="img" aria-label="${esc(roles[index].name)}的日式潑墨Q版全身像" style="--position:${index*50}%"></div>`;}
function scene(level,extra=''){const i=levels.indexOf(level);return `<div class="scene scene-${level} ${extra}" role="img" aria-label="${esc(regions[i]?.name)}潑墨風景" style="--x:${i%3*50}%;--y:${Math.floor(i/3)*100}%"></div>`;}
const fox=()=>'<div class="fox" role="img" aria-label="白狐導師白"></div>';
function audio(text,label='朗讀',slow=false,extra=''){return `<button class="audio" data-audio="${esc(text)}" ${slow?'data-slow="1"':''} ${extra}>${label}</button>`;}
function progress(value,max){return `<div class="progress" role="progressbar" aria-label="學習進度" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="${max}"><span style="width:${max?value/max*100:0}%"></span></div>`;}
function shell(html){screenToken++;stopVoice();root.classList.remove('hide-translations');root.innerHTML=html+'<dialog id="gloss-dialog" class="gloss-dialog"></dialog>';window.scrollTo({top:0,behavior:'instant'});status();}
function leave(){if(((session&&!session.done)||(assessment&&!assessment.done))&&!confirm('這次未完成的小任務會重新開始；已完成的詞與故事會保留。要離開嗎？'))return false;screenToken++;pendingStart=null;session=null;assessment=null;stopVoice();return true;}
function navigate(next){if(!leave())return;view=next;state=read();render();}
function render(){status();({map:mapView,journal:journalView,lexicon:dictionaryView,kana:kanaView,settings:settingsView,roles:roleView,entry:entryView,progress:progressView}[view]??mapView)();}
function shuffled(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function glossaryFor(id){const lesson=lessons[id];const list=[...(Array.isArray(commonGlossary)?commonGlossary:[]),...(lesson?.wordIds??[]).map(key=>byId.get(key)).filter(Boolean).map(w=>({surface:w.word,reading:w.kana,meaning:w.meaning})),...(lesson?.glossary??[])];glossLookup=new Map(list.filter(x=>x.surface&&x.reading).map(x=>[x.surface,x]));}
function jaMarkup(text){if(!text)return '';const keys=[...glossLookup.keys()].sort((a,b)=>b.length-a.length);if(!keys.length)return esc(text);const patterns=keys.map(k=>{const literal=k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return (/^[\p{Script=Han}々]/u.test(k)?'(?<![\\p{Script=Han}々])':'')+literal+(/[\p{Script=Han}々]$/u.test(k)?'(?![\\p{Script=Han}々])':'');});const regex=new RegExp('('+patterns.join('|')+')','gu');return String(text).split(regex).map(part=>{const term=glossLookup.get(part);if(!term)return esc(part);return `<button class="inline-word" data-gloss="${esc(part)}" aria-label="${esc(part)}：查看讀音與意思">${furigana?`<ruby>${esc(part)}<rt>${esc(term.reading)}</rt></ruby>`:esc(part)}</button>`;}).join('');}
function jaReading(text){return jaMarkup(text).replace(/<button[^>]*>/g,'').replace(/<\/button>/g,'');}
function openGloss(key){const term=glossLookup.get(key);if(!term)return;const dialog=$('#gloss-dialog');dialog.innerHTML=`<h2 lang="ja">${esc(term.surface)}</h2><p lang="ja">${esc(term.reading)}</p><p>${esc(term.meaning)}</p><div class="actions">${audio(term.reading,'聽讀音')}<button class="primary" data-action="close-gloss">關閉</button></div>`;dialog.showModal();}
function metrics(){const s=statsSummary(state);return `<div class="metrics"><div><strong>${s.completed.toLocaleString()}</strong><span>完成練習的詞</span></div><div><strong>${s.firstIndependent.toLocaleString()}</strong><span>首次無提示答對</span></div><div><strong>${s.retained.toLocaleString()}</strong><span>隔日無提示答對</span></div><div><strong>${s.due.toLocaleString()}</strong><span>到期需複習</span></div></div>`;}
function journeyProgress(id){
 const e=chapters.find(c=>c.id===id);if(!e)return '';
 const p=chapterProgress(state,id),local=chapters.filter(c=>c.level===e.level),region=regions.find(r=>r.id===e.level),done=local.filter(c=>chapterProgress(state,c.id).cleared).length;
 const known=new Set(learnedIds(state)),tasks=[0,1].map(i=>lessons[id].wordIds.slice(i*5,i*5+5).filter(w=>known.has(w)).length);
 const steps=tasks.filter(n=>n===5).length+Number(p.cleared);
 return `<section class="journey-progress" aria-label="國度與小關進度"><strong>${esc(region.name)} · 已過 ${done} / ${local.length} 小關</strong><p>目前第 ${local.indexOf(e)+1} 小關「${esc(e.title)}」· 完成 ${steps} / 3 個步驟，還差 ${3-steps} 步</p><progress value="${steps}" max="3" aria-label="本小關完成步驟"></progress><p>${tasks[0]===5?'✓':'○'} 任務一 ${tasks[0]}/5 詞　${tasks[1]===5?'✓':'○'} 任務二 ${tasks[1]}/5 詞　${p.cleared?'✓':'○'} 情境考驗 ${p.cleared?'已完成':'3 題待通過'}</p><details><summary>查看本國 ${local.length} 小關完成清單</summary><ol>${local.map(c=>{const cp=chapterProgress(state,c.id);return `<li ${c.id===id?'aria-current="step"':''}>${cp.cleared?'✓ 已完成':cp.skipped?'○ 略過，未完成':c.id===currentChapter(state)?.id?'→ 進行中':'○ 未完成'} · ${esc(c.title)}</li>`;}).join('')}</ol><p>兩組核心詞完成後，還要通過 3 題情境考驗，才算完成一個小關。複習、擴充詞與略過不會直接增加過關數。</p></details></section>`;
}
function journeyThread(id,finished=false){
 const e=chapters.find(c=>c.id===id);if(!e)return '';
 const p=chapterProgress(state,id),choice=e.choices.find(c=>c.id===state.choices[id]),beats=lessons[id].beats[choice?.id]??[],next=currentChapter(state);
 const change=p.cleared?choice?.ending:p.tasksComplete?beats[p.tasksComplete-1]?.zh:choice?'你已作出選擇，接著練習能用來幫忙的言葉。':'先理解眼前的需要，再選擇你要如何幫忙。';
 const upcoming=p.cleared?(next?`下一小關「${next.title}」：${next.summary}`:'本次路線已完成，可以回讀手札或返回略過的章節。'):p.readyForAssessment?`兩組詞彙已完成。接著在 3 題新情境中運用日語：${lessons[id].goal}`:`先完成第 ${(p.nextTask??0)+1} 組五個核心詞，才能展開下一段劇情。這一關的目標是：${lessons[id].goal}`;
 return `<section class="story-thread"><p><b>前情與你的決定</b>　${esc(e.summary)} ${esc(choice?.result??'')}</p><p><b>${finished?'這次的改變':'故事走到這裡'}</b>　${esc(change)}</p><p><b>接下來</b>　${esc(upcoming)}</p></section>`;
}
function mapView(){const c=currentChapter(state),region=regions.find(r=>r.id===selectedLevel)??regions[0],local=chapters.filter(c=>c.level===region.id),role=roles.find(r=>r.id===state.role),summary=statsSummary(state);glossaryFor(c?.id);
 shell(`<section class="hero"><div class="hero-copy"><p class="eyebrow">日式潑墨 · 英雄之旅 · N5 → N1</p><h1>世界忘了文字，<br>你，還記得那道光。</h1><p>與白狐和旅人同行。<br>學會一句能用上的日語，<br>就替故事裡的人，打開一條路。</p><div class="actions"><button class="primary" data-action="continue">${!role?'選擇旅人，啟程':c?`繼續旅程 · ${esc(c.title)}`:'閱讀這條路線的結局'}</button><button class="ghost" data-nav="entry">選擇我的程度</button><button class="ghost" data-nav="kana">零基礎 · 五十音入門</button></div><small>25 章情境主線 · 每章 10 個核心詞 · ${words.length.toLocaleString()} 詞擴充練習</small></div></section>
 <section class="journey-strip"><div>${role?roleArt(role.id,'mini'):fox()}</div><div><span class="eyebrow">${role?`${esc(role.name)} · ${esc(role.title)}`:'每段旅程，都需要一位同行者'}</span><p>${esc(c?.summary??'這次路線已完成，你可以回到其他國度，接續尚未走過的故事。')}</p></div><button data-nav="roles">${role?'查看旅伴':'認識三位旅人'}</button></section>
 <section class="dashboard">${metrics()}<div class="actions"><button class="primary" data-action="review" ${summary.completed?'':'disabled'}>${summary.due?`複習到期詞 · ${summary.due} 詞`:'練習已完成的詞'}</button><button data-nav="progress">查看學習紀錄</button></div><p class="muted">目前起點 ${state.entryLevel}；略過 ${state.skipped.length} 章不計入完成。完成詞數代表練習紀錄，不等於已通過日語檢定。</p>${state.legacyImported?'<p class="tip">已讀入舊版詞彙與故事紀錄；新版情境考驗另行記錄，不會把舊進度當成新測驗成績。</p>':''}</section>
 <section class="world"><div class="section-heading"><div><p class="eyebrow">每五個詞，讓故事前進一步</p><h2>五國旅圖</h2></div><span class="muted">情境考驗完成 ${summary.chaptersCleared} / 25 章</span></div><div class="level-tabs" role="group" aria-label="國度與日語等級">${regions.map(r=>`<button data-level="${r.id}" class="${selectedLevel===r.id?'selected':''}"><strong>${r.id}</strong>${esc(r.name)}<small>${counts[r.id].toLocaleString()} 詞</small></button>`).join('')}</div>
 <div class="realm-panel">${scene(region.id)}<div><p class="eyebrow">${region.id} · ${esc(region.subtitle)}</p><h2>${esc(region.name)}</h2><p>${esc(region.description)}</p><div class="actions"><button data-entry-level="${region.id}">從 ${region.id} 開始／接續主線</button><button data-browse-level="${region.id}">自由查詞與擴充練習</button></div></div></div>
 <p class="journey-progress"><strong>${esc(region.name)} · 已完成 ${local.filter(c=>chapterProgress(state,c.id).cleared).length} / ${local.length} 小關</strong>每小關包含兩組五詞任務與三題情境考驗；下方逐關顯示完成狀態。</p><div class="chapter-list">${local.map((e,i)=>{const p=chapterProgress(state,e.id),unlocked=e.id===c?.id||p.cleared;return `<button class="chapter ${p.cleared?'completed':unlocked?'current':''}" data-episode="${e.id}"><span class="chapter-number">${String(i+1).padStart(2,'0')}</span><span><small>${esc(e.beat)}</small><strong>${esc(e.title)}</strong><small>${esc(lessons[e.id]?.goal)} · ${p.total} 個核心詞</small></span><span class="chapter-state">${p.cleared?'情境完成':p.skipped?'略過 · 可返回':unlocked?`${p.tasksComplete}/${p.tasksTotal} 任務 · 進入`:'劇情預覽'}</span></button>`;}).join('')}</div></section>`);
}
function entryView(){shell(`<section class="panel"><p class="eyebrow">從適合你的地方開始</p><h1>你想從哪裡啟程？</h1><p>這是自主選擇起點，不是能力認證。前面的章節會標為略過，不會增加完成詞數；以後可返回補學，已完成的詞與考驗都會保留。</p><div class="entry-grid"><button class="primary" data-nav="kana"><strong>我還不會五十音</strong><span>從逐行辨讀、拼排到回想；隨時可跳過。</span></button>${regions.map(r=>`<button data-entry-level="${r.id}"><strong>${r.id} · ${esc(r.name)}</strong><span>${r.id==='N5'?'已認識假名，開始日常情境':`已有基礎，直接開始 ${r.id} 情境`}</span></button>`).join('')}</div><p class="muted">故事的情境核心詞會依需要跨級複現；單詞來源分級與故事閱讀難度分開看待。</p><button data-nav="map">回旅圖</button></section>`);}
function roleView(){shell(`<section class="page-title"><p class="eyebrow">同一條路，三種看見世界的方式</p><h1>誰，將替這個世界寫下下一頁？</h1><p>角色提供不同觀察。每章的抉擇還會改變後續微劇情與日語情境任務。</p></section><section class="role-grid">${roles.map(r=>`<article class="role-card ${state.role===r.id?'selected':''}">${roleArt(r.id)}<div class="role-copy"><p class="eyebrow">${esc(r.title)}</p><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><p class="trait">${esc(r.trait)}</p><button class="primary" data-role="${r.id}">${state.role===r.id?'繼續同行':'與我同行'}</button></div></article>`).join('')}</section><div class="mentor">${fox()}<p>白：「不是最勇敢的人才能出發。<br>願意說出第一句話的人，就已經在路上了。」</p></div>`);}
function continueJourney(){state=read();if(!state.role){view='roles';roleView();return;}const c=currentChapter(state);if(c){selectedLevel=c.level;episodeView(c.id);}else endingView();}
function episodeView(id){const e=chapters.find(c=>c.id===id);if(!e)return;activeEpisode=id;view='episode';glossaryFor(id);const lesson=lessons[id],p=chapterProgress(state,id),idx=chapters.indexOf(e),unlocked=currentChapter(state)?.id===id,choice=e.choices.find(x=>x.id===state.choices[id]),role=roles.find(r=>r.id===state.role),previous=chapters[idx-1],echo=previous&&chapterProgress(state,previous.id).cleared?previous.choices.find(x=>x.id===state.choices[previous.id]):null;
 shell(`<section class="story-layout"><aside class="story-aside">${scene(e.level)}<div class="story-guide">${role?roleArt(role.id,'small'):fox()}<div><p class="eyebrow">${esc(role?.name??'白')}的視角</p><p>${esc(e.roleNotes[state.role]??e.summary)}</p></div></div><button data-nav="map">返回旅圖</button></aside><article class="story-paper"><p class="eyebrow">${e.level} · ${esc(e.beat)} · 第 ${idx+1} / 25 章</p><h1>${esc(e.title)}</h1>${journeyProgress(id)}${journeyThread(id)}<section class="can-do"><strong>這一章，我能做到</strong><p>${esc(lesson.goal)}</p><p>10 個核心詞 → 2 次劇情推進 → 3 題新情境考驗</p></section>${!unlocked&&!p.cleared?`<p class="tip">${p.skipped?'這一章目前略過。':'這是故事預覽。'}<button data-entry-level="${e.level}">從 ${e.level} 開始／接續</button></p>`:''}${p.legacyCleared&&!p.cleared?'<p class="tip">保留你的舊版章節紀錄；新版情境考驗尚未完成。</p>':''}${echo?`<blockquote><small>前一段旅途的回聲</small><p>${esc(echo.echo)}</p></blockquote>`:''}<div class="audio-bar">${audio(e.paragraphs.map(p=>p.ja).join('\n'),'聽完整日文故事')}${audio(e.paragraphs.map(p=>p.ja).join('\n'),'慢速',true)}<button data-action="stop">停止</button><button id="translation-toggle">隱藏中文</button><button id="furigana-toggle">${furigana?'隱藏':'顯示'}振假名</button></div><p class="muted">點有底線的詞，可以查看讀音與意思。中文是學習支援，情境考驗會改用新材料。</p><div class="story-text">${e.paragraphs.map(p=>`<div class="paragraph"><p lang="ja">${jaMarkup(p.ja)}</p><p class="translation">${esc(p.zh)}</p></div>`).join('')}</div><div class="dialogue">${fox()}<div>${e.dialogue.map(d=>`<p><strong>${esc(roles.find(r=>r.id===d.speaker)?.name??'白')}：</strong><span lang="ja">${jaMarkup(d.ja)}</span></p><p class="translation">${esc(d.zh)}</p>${audio(d.ja,'聽對話')}`).join('')}</div></div>
 <section class="grammar-card"><p class="eyebrow">帶著這個句型，走進情境</p><h3 lang="ja">${esc(lesson.grammar.pattern)}</h3><p>${esc(lesson.grammar.explanation)}</p><p lang="ja">${jaMarkup(lesson.grammar.example)}</p><p>${esc(lesson.grammar.translation)}</p>${audio(lesson.grammar.example,'聽句型示範')}</section>
 <section class="decision"><p class="eyebrow">你的抉擇，會帶來不同的日語任務</p>${choice?`<h3>${esc(choice.label)}</h3><p>${esc(choice.result)}</p>`:`<h3>你想怎麼做？</h3><div class="choices">${e.choices.map(o=>`<button data-choice="${o.id}" ${!unlocked||!role?'disabled':''}>${esc(o.label)}</button>`).join('')}</div>${!role?'<button data-nav="roles">先選擇你的旅人</button>':''}`}</section>
 ${choice?`<section class="story-beats"><h3>一路留下的足跡</h3>${(lesson.beats[choice.id]??[]).map((beat,i)=>`<article class="micro-story ${p.tasksComplete>i?'revealed':''}"><strong>第 ${i+1} 步 · ${p.tasksComplete>i?'已展開':'完成下一組核心詞後展開'}</strong>${p.tasksComplete>i?`<p lang="ja">${jaMarkup(beat.ja)}</p><p>${esc(beat.zh)}</p>${audio(beat.ja,'聽這段故事')}`:''}</article>`).join('')}</section>`:''}
 <section class="chapter-mission"><h3>把本章 ${p.total} 個核心詞用起來</h3>${progress(p.tasksComplete,p.tasksTotal)}<small>${p.tasksComplete} / ${p.tasksTotal} 個小任務</small><div class="target-words">${lesson.wordIds.map(id=>{const w=byId.get(id);return `<button data-word="${id}">${esc(w.word)}<small>${esc(w.kana)}</small></button>`;}).join('')}</div><div class="actions">${!p.cleared&&unlocked&&choice?`<button class="primary" data-action="${p.readyForAssessment?'story-quiz':'learn'}">${p.readyForAssessment?'開始三題日語情境考驗':'出發 · 練習五個核心詞'}</button>`:''}<button data-browse-level="${e.level}">${e.level} 擴充詞庫</button>${p.cleared?`<span class="reward">✓ ${esc(e.reward)}</span>`:''}</div></section></article></section>`);
 $('#translation-toggle').onclick=()=>{root.classList.toggle('hide-translations');$('#translation-toggle').textContent=root.classList.contains('hide-translations')?'顯示中文':'隱藏中文';};$('#furigana-toggle').onclick=()=>{furigana=!furigana;episodeView(id);};
}
function begin(options={}){try{state=read();if(!state.role){pendingStart=options;view='roles';roleView();return;}assessment=null;session=start(state,{...options,listening:!!japaneseVoice()});session.isPractice=options.practice===true;session.practiceLevel=options.level??selectedLevel;if(!session.queue.length){notify('目前沒有可練習的詞，請先完成一組主線或選另一個等級。');session=null;return;}learnIndex=0;session.fresh.length?learnView():questionView();}catch(e){notify(e.message);session=null;continueJourney();}}
function learnView(){const w=session.fresh[learnIndex],e=chapters.find(e=>e.id===session.chapterId),lesson=lessons[e?.id];glossaryFor(e?.id);shell(`<section class="lesson-layout"><aside class="lesson-guide">${roleArt(state.role,'lesson-role')}<p class="eyebrow">${session.isPractice?`${session.practiceLevel} 擴充練習`:esc(e?.title??'旅途複習')}</p><h2>讀、聽，再試著想起來。</h2><p>${esc(lesson?.goal??'把完整詞庫裡的言葉，慢慢收進自己的行囊。')}</p>${lesson?`<p class="tip">本章句型：<span lang="ja">${esc(lesson.grammar.pattern)}</span></p>`:''}<small>本次 ${session.fresh.length} 詞 · 全站 ${words.length.toLocaleString()} 詞</small><button data-nav="map">返回旅圖</button></aside><article class="word-paper">${session.kind==='core'?journeyProgress(session.chapterId):''}<p class="eyebrow">來源參考級別 ${w.level} · 詞卡 ${learnIndex+1} / ${session.fresh.length}</p>${progress(learnIndex+1,session.fresh.length)}<h1 lang="ja" class="word">${esc(w.word)}</h1><p lang="ja" class="reading">${esc(w.kana)}</p><p class="meaning">${esc(w.meaning)}</p>${w.usageNote?`<p class="tip">${esc(w.usageNote)}</p>`:''}<div class="audio-bar">${audio(w.kana,'聽讀音')}${audio(w.kana,'慢速',true)}<button data-action="stop">停止</button></div><div class="example"><p lang="ja">${jaMarkup(w.example)}</p><p>${esc(w.translation)}</p>${audio(w.example,'聽語例')}<small>${w.exampleSource==='original'?'本站原創補充例句':'來源語例；部分為短語'}</small></div><p class="muted">先看示範、跟著讀一次。接著練意思與假名回想；需要時可使用提示與拼排引導。</p><div class="actions"><button class="primary" id="learn-next">${learnIndex===session.fresh.length-1?'開始旅途練習':'下一個詞'}</button></div></article></section>`);$('#learn-next').onclick=()=>{stopVoice();++learnIndex<session.fresh.length?learnView():questionView();};}
function questionView(){const q=session.queue[0];if(!q){finish();return;}const w=byId.get(q.id),reading=q.mode==='reading',listen=q.mode==='listening'&&!q.uiFallback;const distractors=shuffled(distractorPool(w,words));const meanings=shuffled([w.meaning,...[...new Set(distractors.map(x=>x.meaning))].slice(0,3)]);
 shell(`<section class="panel quiz">${session.kind==='core'?journeyProgress(session.chapterId):''}<p class="eyebrow">${q.review?'旅途複習':'言葉練習'} · 還有 ${session.queue.length} 題</p><h1>${reading?'回想這個詞的假名讀音。':listen?'聽見了什麼言葉？':'這個言葉，帶著什麼意思？'}</h1><p class="muted">${reading?'輸入假名。平假名、片假名皆可；不接受羅馬拼音。提示與拼排會記為有協助的練習。':listen?'先按播放，聽完再選出意思。':'讀一讀，再選出意思。'}</p><div class="quiz-word">${reading?`<p class="meaning">${esc(w.meaning)}</p>${readingCue(w,words)?`<p class="reading" lang="ja">本題指定：${esc(w.word)}</p>`:''}`:listen?`<div class="listen-symbol">音</div>${audio(w.kana,'播放日語')}${audio(w.kana,'慢速',true)}<button id="text-mode">改用文字題（另行記錄）</button>`:`<p lang="ja" class="word">${esc(w.word)}</p><p lang="ja" class="reading">${esc(w.kana)}</p>`}</div>
 ${reading?`<form id="reading-form"><label for="reading-input">日文假名</label><input id="reading-input" autocomplete="off" lang="ja" required><div class="actions"><button class="primary" type="submit">確認答案</button><button type="button" id="hint">需要提示</button>${audio(w.kana,'聽提示',false,'data-hint-audio="1"')}<button type="button" id="guided-spelling">新手：先拼排，再回想</button></div><p id="hint-text" class="muted"></p><div id="spelling-guide"></div><details class="kana-keyboard"><summary>沒有日文鍵盤？展開假名小鍵盤</summary><div>${[...'あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをんがぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽゃゅょっぁぃぅぇぉー'].map(k=>`<button type="button" data-key="${k}">${k}</button>`).join('')}<button type="button" data-key="back">退一字</button></div></details></form>`:`<p class="muted">${choiceHint}</p><div class="choices" data-quiz-options>${meanings.map((m,i)=>`<button data-quiz-choice data-answer="${esc(m)}"><small>${"ABCD"[i]}</small> ${esc(m)}</button>`).join('')}</div>`}<p id="feedback" class="feedback" role="status"></p><button class="primary" id="next" hidden>繼續</button><button class="quiet" data-nav="map">回旅圖</button></section>`);
 if(reading){$('#reading-form').onsubmit=e=>{e.preventDefault();submit($('#reading-input').value);};$('#hint').onclick=async()=>{const active=session,token=screenToken;markHint(active);await persistEvidence(active);if(active!==session||token!==screenToken)return;$('#hint-text').textContent=`跟著讀一次：${w.kana}（本題已使用提示）`;};$('#guided-spelling').onclick=()=>spellingGuide(w);}
 if(listen)$('#text-mode').onclick=async()=>{const active=session,token=screenToken;markFallback(active);q.uiFallback=true;await persistEvidence(active);if(active!==session||token!==screenToken)return;stopVoice();questionView();};$('#next').onclick=async()=>{const active=session,token=screenToken;if(!await persistEvidence(active)||active!==session||token!==screenToken)return;active.awaitingExplanation=false;stopVoice();return active.done?finish():questionView();};
}
async function spellingGuide(w){const active=session,token=screenToken;markHint(active);await persistEvidence(active);if(active!==session||token!==screenToken)return;const target=[...w.kana],tokens=shuffled(target.map((char,i)=>({char,i}))),picked=[];const box=$('#spelling-guide');box.innerHTML=`<section class="tip"><strong>先看示範：<span lang="ja">${esc(w.kana)}</span></strong><p>照讀音順序點選假名，完成後撤掉示範，再回想一次。本題會記錄為使用引導。</p><p id="spelled" lang="ja" class="reading"></p><div class="spelling-tiles">${tokens.map(t=>`<button type="button" data-spell="${t.i}">${esc(t.char)}</button>`).join('')}</div><button type="button" id="spell-reset">重新拼排</button><button type="button" id="spell-check">檢查拼排</button><p id="spell-feedback" role="status"></p></section>`;box.querySelectorAll('[data-spell]').forEach(b=>b.onclick=()=>{picked.push(target[Number(b.dataset.spell)]);b.disabled=true;$('#spelled').textContent=picked.join('');});$('#spell-reset').onclick=()=>{picked.length=0;$('#spelled').textContent='';box.querySelectorAll('[data-spell]').forEach(b=>b.disabled=false);$('#spell-feedback').textContent='';};$('#spell-check').onclick=()=>{if(picked.join('')!==w.kana){$('#spell-feedback').textContent='順序還不一樣，看看示範，再排一次。';return;}box.innerHTML='<p class="feedback">拼排完成。示範已收起，請在上方輸入框回想假名。</p>';$('#hint-text').textContent='本題已使用拼排引導。';$('#reading-input').value='';$('#reading-input').focus();};}
async function submit(value){const active=session,token=screenToken;if(!active||active.submitting||active.awaitingExplanation)return;active.submitting=true;const answeredWord=byId.get(active.queue[0]?.id),r=answer(active,value);if(!r)return;root.querySelectorAll('.choices button,form button,form input').forEach(el=>el.disabled=true);const saved=await persistEvidence(active);active.submitting=false;if(active!==session||token!==screenToken)return;if(r.ok&&saved){stopVoice();return active.done?finish():questionView();}active.awaitingExplanation=true;$('#feedback').className=`feedback ${r.ok?'':'wrong'}`;$('#feedback').textContent=r.ok?'答對了。這個言葉，又亮了一點。':`正確答案是「${r.expected}」。${answeredWord.word}（${answeredWord.kana}）的意思是「${answeredWord.meaning}」。${answeredWord.example||''} ${answeredWord.translation||''} 稍後會再練一次。`;$('#next').hidden=false;$('#next').focus();}
async function finish(){
 const completed=session,token=screenToken;if(!completed||completed.saving)return;completed.saving=true;
 const beforeState=read(),before=new Set(learnedIds(beforeState)),tasksBefore=completed.chapterId?chapterProgress(beforeState,completed.chapterId).tasksComplete:0;
 let saved;try{saved=await mutate(s=>commit(s,completed));}finally{completed.saving=false;}
 if(completed!==session||token!==screenToken)return;
 const chapter=chapters.find(c=>c.id===completed.chapterId),p=chapter?chapterProgress(state,chapter.id):null,lesson=lessons[chapter?.id],choice=state.choices[chapter?.id];
 const advanced=saved&&completed.kind==='core'&&p?.tasksComplete>tasksBefore,beat=advanced?lesson?.beats[choice]?.[p.tasksComplete-1]:null,newCount=saved?completed.fresh.filter(w=>!before.has(w.id)).length:0;glossaryFor(chapter?.id);
 shell(`<section class="panel achievement">${fox()}<p class="eyebrow">${saved?'旅程已保存':'儲存未成功，請留在本頁重試'}</p><h1>${beat?'你的日語，讓故事前進了一步。':completed.kind==='review'?'複習完成，讓言葉再亮一次。':'微小的言葉，也能點亮一條路。'}</h1><p>新增完成 ${newCount} 詞，複習 ${new Set(completed.reviewed??[]).size} 詞。這次重試 ${completed.retries} 次。</p>${beat?`<article class="micro-story revealed"><p lang="ja">${jaMarkup(beat.ja)}</p><p>${esc(beat.zh)}</p>${audio(beat.ja,'聽新劇情')}</article>`:'<p>每次看過與答過，都留下不同的練習證據；隔日再回來試試。</p>'}${completed.kind==='core'?journeyProgress(chapter?.id)+journeyThread(chapter?.id,true):''}${metrics()}<div class="actions">${saved?(completed.kind==='practice'?`<button class="primary" data-practice-level="${completed.practiceLevel}">再練五個擴充詞</button>`:completed.kind==='review'?'<button class="primary" data-action="review">再複習一組</button>':p?`<button class="primary" data-action="${p.readyForAssessment?'story-quiz':'learn'}">${p.readyForAssessment?'運用日語 · 進入情境考驗':'繼續下一段旅程'}</button>`:'<button class="primary" data-action="continue">繼續旅程</button>'):'<button class="primary" data-action="save-retry">重試儲存</button>'}<button data-nav="map">回旅圖休息</button></div></section>`);if(saved)session=null;
}
function storyQuiz(){try{session=null;state=read();assessment=startAssessment(state);activeEpisode=assessment.chapterId;assessmentView();}catch(e){notify(e.message);continueJourney();}}
function assessmentView(){if(!assessment.queue.length){finishAssessment();return;}const q=assessment.queue[0],e=chapters.find(c=>c.id===assessment.chapterId),isListening=q.mode==='listening';if(isListening&&!japaneseVoice()&&!q.uiFallback){q.uiFallback=true;markFallback(assessment);void persistEvidence(assessment);}glossaryFor(e.id);shell(`<section class="panel assessment">${journeyProgress(e.id)}<p class="eyebrow">${esc(e.title)} · 新情境考驗 · 尚有 ${assessment.queue.length} 題</p><h1>${q.mode==='response'?'把日語用在這一刻。':isListening?'聽懂這次的需要。':'讀懂新的線索。'}</h1><p>${esc(q.prompt)}</p><p class="muted">這是本章以外的新材料。作答前不提供中譯；答題後可看說明。首次作答與文字替代會分開記錄。</p>${isListening&&!q.uiFallback?`<div class="listening-material">${audio(q.ja,'播放情境對話')}${audio(q.ja,'慢速',true)}<button id="assessment-text">改用文字材料</button></div>`:`${isListening?'<p class="tip">文字替代模式：本題記為閱讀，不記為聽解。</p>':''}<div class="assessment-material" lang="ja">${e.level==='N5'?jaReading(q.ja):esc(q.ja)}</div>`}<p class="muted">${choiceHint}</p><div class="choices" data-quiz-options>${q.options.map((o,i)=>`<button data-quiz-choice data-assessment-answer="${i}"><small>${"ABCD"[i]}</small> ${e.level==='N5'?jaReading(o):esc(o)}</button>`).join('')}</div><p class="feedback" id="assessment-feedback" role="status"></p><div id="assessment-explanation"></div><button class="primary" id="assessment-next" hidden>繼續情境考驗</button><button class="quiet" data-episode="${e.id}">回到本章學習</button></section>`);if($('#assessment-text'))$('#assessment-text').onclick=async()=>{const active=assessment,token=screenToken;q.uiFallback=true;markFallback(active);await persistEvidence(active);if(active!==assessment||token!==screenToken)return;assessmentView();};$('#assessment-next').onclick=async()=>{const active=assessment,token=screenToken;if(!await persistEvidence(active)||active!==assessment||token!==screenToken)return;active.awaitingExplanation=false;return active.done?finishAssessment():assessmentView();};}
async function submitAssessment(index){const active=assessment,token=screenToken;if(!active||active.submitting||active.awaitingExplanation)return;active.submitting=true;const q=active.queue[0],result=answerAssessment(active,Number(index),{fallback:q.uiFallback===true});root.querySelectorAll('[data-assessment-answer]').forEach(b=>b.disabled=true);const saved=await persistEvidence(active);active.submitting=false;if(active!==assessment||token!==screenToken)return;if(result.ok&&saved){stopVoice();return active.done?finishAssessment():assessmentView();}active.awaitingExplanation=true;$('#assessment-feedback').className=`feedback ${result.ok?'':'wrong'}`;$('#assessment-feedback').textContent=result.ok?'你理解了這次的需要。':'先看線索與說明，稍後會再練一次。';$('#assessment-explanation').innerHTML=`<div class="tip"><p lang="ja">${jaMarkup(q.ja)}</p><p>${esc(q.translation)}</p><p>${esc(result.explanation??q.explanation)}</p><p>合適的回應：${esc(q.options[q.answer])}</p></div>`;$('#assessment-next').hidden=false;$('#assessment-next').focus();}
async function finishAssessment(){const finished=assessment,token=screenToken;if(!finished||finished.saving)return;finished.saving=true;let saved;try{saved=await mutate(s=>commitAssessment(s,finished));}finally{finished.saving=false;}if(finished!==assessment||token!==screenToken)return;if(!saved){notify('尚未儲存，請重試。');return;}const e=chapters.find(c=>c.id===finished.chapterId),summary=statsSummary(state);assessment=null;shell(`<section class="panel achievement">${fox()}<p class="eyebrow">三題情境練習完成</p><h1>你取得了「${esc(e.reward)}」</h1>${journeyProgress(e.id)}${journeyThread(e.id,true)}<p>${esc(lessons[e.id].goal)}</p><p>${esc(e.choices.find(x=>x.id===state.choices[e.id])?.ending)}</p><p class="muted">這是本站單元練習紀錄，不代表通過 JLPT 等級。答錯後重試與文字替代都會留在學習紀錄裡。</p><div class="actions"><button class="primary" data-action="continue">${summary.routeComplete?'閱讀這條路線的結局':'走向下一章'}</button><button data-nav="progress">查看首次作答紀錄</button><button data-nav="journal">收進故事手札</button></div></section>`);}
function dictionaryView(){const learned=new Set(learnedIds(state)),query=searchTerm.trim().toLocaleLowerCase();const matches=words.filter(w=>(dictionaryLevel==='all'||w.level===dictionaryLevel)&&(!onlyLearned||learned.has(w.id))&&(!query||[w.word,w.kana,w.meaning].some(v=>v.toLocaleLowerCase().includes(query))));const pages=Math.max(1,Math.ceil(matches.length/24));page=Math.min(page,pages-1);const shown=matches.slice(page*24,page*24+24),practiceLevel=dictionaryLevel==='all'?selectedLevel:dictionaryLevel;
 shell(`<section class="page-title"><p class="eyebrow">把沿途的言葉，收進自己的行囊</p><h1>言葉辭典與擴充練習</h1><p>完整 ${words.length.toLocaleString()} 詞都保留。查詞不計完成；進入五詞練習並完成後，才留下紀錄。擴充練習不用先走完前一級。</p></section><form id="search-form" class="search-bar"><label for="search">日文、假名或中文</label><input id="search" value="${esc(searchTerm)}" placeholder="例如：ありがとう、感謝"><label for="filter">等級</label><select id="filter"><option value="all">全部等級</option>${levels.map(l=>`<option ${dictionaryLevel===l?'selected':''}>${l}</option>`).join('')}</select><button class="primary">搜尋</button><label class="check"><input id="only-learned" type="checkbox" ${onlyLearned?'checked':''}>只看完成練習的詞</label></form><div class="section-heading"><p>找到 ${matches.length.toLocaleString()} 詞 · 第 ${page+1} / ${pages} 頁</p><div class="actions"><button class="primary" data-practice-level="${practiceLevel}">練習 ${practiceLevel} 擴充詞 · 五詞一組</button><button data-action="review" ${learned.size?'':'disabled'}>複習到期詞</button></div></div><p class="muted">擴充任務從所選等級尚未完成的詞依序安排，不限於目前搜尋結果。</p><div class="dictionary-grid">${shown.map(w=>`<article class="dictionary-card"><span class="badge">來源 ${w.level}${learned.has(w.id)?' · 已完成練習':''}</span><h2 lang="ja">${esc(w.word)}</h2><p lang="ja">${esc(w.kana)}</p><p>${esc(w.meaning)}</p><div class="audio-bar">${audio(w.kana,'聽讀音')}<button data-word="${w.id}">語例與詳情</button></div></article>`).join('')||'<p class="empty">沒有符合的詞，換個關鍵字試試。</p>'}</div><div class="pagination"><button id="prev-page" ${page===0?'disabled':''}>上一頁</button><span>${page+1} / ${pages}</span><button id="next-page" ${page>=pages-1?'disabled':''}>下一頁</button></div>`);
 $('#search-form').onsubmit=e=>{e.preventDefault();searchTerm=$('#search').value;dictionaryLevel=$('#filter').value;onlyLearned=$('#only-learned').checked;page=0;dictionaryView();};$('#filter').onchange=()=>$('#search-form').requestSubmit();$('#only-learned').onchange=()=>$('#search-form').requestSubmit();$('#prev-page').onclick=()=>{page--;dictionaryView();};$('#next-page').onclick=()=>{page++;dictionaryView();};
}
function wordView(id){const w=byId.get(id);if(!w)return;const e=chapters.find(c=>c.id===activeEpisode);glossaryFor(e?.id);shell(`<article class="panel word-detail"><span class="badge">來源參考級別 ${w.level}</span><h1 class="word" lang="ja">${esc(w.word)}</h1><p lang="ja" class="reading">${esc(w.kana)}</p><p class="meaning">${esc(w.meaning)}</p>${w.usageNote?`<p class="tip">${esc(w.usageNote)}</p>`:''}<div class="audio-bar">${audio(w.kana,'聽讀音')}${audio(w.kana,'慢速',true)}<button data-action="stop">停止</button></div><div class="example"><p lang="ja">${jaMarkup(w.example)}</p><p>${esc(w.translation)}</p>${audio(w.example,'聽語例')}<small>${w.exampleSource==='original'?'例句為本站原創補充':'來源語例；部分為短語'}</small></div><small class="muted">詞條來源：egg rolls · 社群參考級別 ${esc((w.sourceLevels??[w.level]).join('／'))}</small><div class="actions">${e?`<button data-episode="${e.id}">回本章故事</button>`:''}<button data-nav="lexicon">回言葉辭典</button></div></article>`);}
function progressView(){const s=statsSummary(state);const weak=Object.entries(state.stats).filter(([,x])=>x.mistakes>0||x.hints>0).sort((a,b)=>(b[1].mistakes+b[1].hints)-(a[1].mistakes+a[1].hints)).slice(0,20);shell(`<section class="panel"><p class="eyebrow">看見完成，也看見還需要的練習</p><h1>我的學習紀錄</h1>${metrics()}<ul class="evidence-notes"><li>完成練習：整組任務完成，才計入唯一詞數。</li><li>首次無提示答對：首次完成該詞時，意思／聽辨與假名題都一次答對，且未使用提示。</li><li>隔日無提示答對：距上次練習至少 24 小時後，該詞的複習題首次無提示答對。這是單次表現紀錄，不是永久熟練認證。</li><li>文字替代不當成聽力；提示、拼排及錯答都會保留。</li></ul><div class="actions"><button class="primary" data-action="review" ${s.completed?'':'disabled'}>${s.due?`複習 ${s.due} 個到期詞`:'練習最久未複習的詞'}</button><button data-nav="entry">調整程度起點</button></div><h2>需要再相見的詞</h2><p>優先顯示曾答錯或需要提示的前 20 詞。下次到期時，系統先安排最久沒複習的詞。</p><div class="weak-words">${weak.map(([id,x])=>`<button data-word="${id}"><strong lang="ja">${esc(byId.get(id)?.word)}</strong><span>錯答 ${x.mistakes} 次 · 提示 ${x.hints} 次</span></button>`).join('')||'<p>還沒有錯答或提示紀錄。舊版匯入不會推定首次成績。</p>'}</div><h2>日語情境考驗</h2><div class="assessment-records">${chapters.filter(c=>state.assessments[c.id]).map(c=>{const a=state.assessments[c.id],answers=a.answers??[];return `<article><h3>${esc(c.title)}</h3><p>${answers.filter(x=>x.firstCorrect&&!x.hints).length} / ${answers.length} 題首次無提示答對；${answers.filter(x=>x.fallback).length} 題採文字替代。</p><button data-episode="${c.id}">重讀故事</button></article>`;}).join('')||'<p>完成本章核心詞後，再用三個新情境確認理解。</p>'}</div>${state.legacyImported?`<p class="tip">保留 ${state.legacyImported.completed} 個舊版完成詞與 ${state.legacyImported.cleared.length} 章舊紀錄；缺少的首次作答資料不補造。</p>`:''}<p>以上只記錄本裝置練習，不能用來推定 JLPT 成績或實際口說能力。</p><button data-nav="map">回旅圖</button></section>`);}
function journalView(){const summary=statsSummary(state);shell(`<section class="page-title"><p class="eyebrow">抉擇不是消失了，它正在別處發芽</p><h1>故事手札</h1><p>完成 ${summary.chaptersCleared} / 25 章新情境考驗；目前略過 ${state.skipped.length} 章，可隨時返回。</p></section><div class="journal-grid">${chapters.filter(c=>state.choices[c.id]).map(c=>{const choice=c.choices.find(o=>o.id===state.choices[c.id]),p=chapterProgress(state,c.id),idx=chapters.indexOf(c),next=chapters[idx+1],echoReached=choice.echoAt==='epilogue'?p.cleared:!!(state.choices[choice.echoAt]||chapterProgress(state,choice.echoAt).cleared);return `<article class="journal-card"><p class="eyebrow">${c.level} · ${esc(c.beat)}</p><h2>${esc(c.title)}</h2><strong>${esc(choice.label)}</strong><p>${esc(choice.result)}</p>${echoReached?`<blockquote>${esc(choice.echo)}</blockquote>`:'<p class="muted">選擇的回聲，會在後續旅途展開。</p>'}<span class="reward">${p.cleared?`✓ ${esc(c.reward)}`:p.legacyCleared?'舊版已走過 · 新情境待完成':'旅途進行中'}</span><button data-episode="${c.id}">重讀這一章</button></article>`;}).join('')||`<div class="panel">${fox()}<p>手札的第一頁還是空白。帶上你的旅人，寫下第一個決定。</p><button class="primary" data-action="continue">寫下序章</button></div>`}</div>${summary.routeComplete?'<button class="primary" data-action="ending">閱讀這條路線的結局</button>':''}`);}
function endingView(){const summary=statsSummary(state);if(!summary.routeComplete){journalView();return;}const finished=chapters.filter(c=>chapterProgress(state,c.id).cleared);shell(`<section class="ending"><div class="ending-copy"><p class="eyebrow">英雄之旅 · 帶著禮物歸返</p><h1>你帶回的，<br>是能用上的言葉。</h1><p>空白的卷軸有了聲音。<br>而下一頁，是你願意繼續練習的那一句話。</p><p>情境完成 ${summary.chaptersCleared} / 25 章 · 詞彙練習 ${summary.completed.toLocaleString()} / ${words.length.toLocaleString()} 詞</p><p>${summary.journeyComplete?'五國情境主線已完成。':`本次 ${state.entryLevel} 起點路線完成；前方略過 ${state.skipped.length} 章，仍可返回補學。`}</p></div></section><section class="panel"><h2>你的選擇，回到了家</h2>${finished.map(c=>{const o=c.choices.find(x=>x.id===state.choices[c.id]);return `<div class="ending-echo"><h3>${esc(c.title)} · ${esc(c.reward)}</h3><p>${esc(o?.ending)}</p></div>`;}).join('')}<div class="actions"><button data-nav="entry">回到其他國度</button><button data-nav="lexicon">繼續擴充詞彙</button><button class="primary" data-action="review">讓言葉留在心裡 · 複習</button></div></section>`);}
function kanaView(){view='kana';mountKana({root,shell,esc,audio,speak,stopVoice,notify,getProgress:()=>read().kana,saveProgress:next=>mutate(s=>({...s,kana:next})),onContinue:()=>{view='map';continueJourney();},hasVoice:()=>!!japaneseVoice()});}
function download(raw,name){const blob=new Blob([raw],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function settingsView(){const s=statsSummary(state);shell(`<section class="panel"><p class="eyebrow">讓這段旅程，安心留在身邊</p><h1>旅程設定與備份</h1><h2>你的旅程</h2><p>完成練習 ${s.completed.toLocaleString()} 詞 · 新情境考驗 ${s.chaptersCleared}/25 章。現在起點 ${state.entryLevel}。</p><p>進度僅存在這個瀏覽器，尚未提供登入與跨裝置同步。</p><p class="tip">新版使用獨立 v3 存檔，保留原 v2。舊版已完成詞與故事會遷移；新情境考驗及首次作答證據另外累積。</p>${storageProblem?'<p class="feedback wrong">現有存檔無法讀取，已停止覆寫。請先下載原始資料，再匯入有效備份。</p>':''}<div class="actions"><button class="primary" id="export">下載旅程備份</button><button id="export-raw">下載原始存檔</button><label class="file-button">匯入旅程備份<input id="import" type="file" accept="application/json,.json"></label></div><button data-nav="progress">查看學習證據</button><h2>日語朗讀</h2><p id="voice-status">${japaneseVoice()?`目前聲線：${esc(japaneseVoice().name)}`:'尚未偵測到日語聲線。請先在裝置語音設定安裝日語；仍可使用文字練習，文字替代不記為聽解。'}</p><div class="audio-bar">${audio('こんにちは。ことばをさがすたびにでましょう。','試聽日語')}${audio('こんにちは。ことばをさがすたびにでましょう。','慢速',true)}<button data-action="stop">停止</button></div><p>朗讀採裝置日語聲線，本站未內建錄製音檔；聲線是否需要網路依裝置而定。</p><h2>關於詞彙與故事</h2><p>全庫 ${words.length.toLocaleString()} 詞。原來源缺例句的 122 詞已補本站原創例句；其他來源語例可能是短語。點開詞條可辨識原創補充。資料分級是社群參考，不是官方考試清單。</p><p>25 章各有目標、句型、10 核心詞與 3 題新情境；兩種抉擇具有不同微劇情及任務。核心詞依情境跨級選配，和詞庫來源分級分開。</p><p>已修正抽查發現的搭配、中譯與語用問題；這仍不是真人教師逐詞審定、正式JLPT課程或學習成效認證。</p><a href="THIRD-PARTY-NOTICES.md" target="_blank" rel="noopener">查看來源與補充說明</a></section>`);
 $('#export').onclick=()=>download(JSON.stringify(read(),null,2),'nihongo-odyssey-v3.json');$('#export-raw').onclick=()=>{try{download(localStorage.getItem(KEY)??localStorage.getItem(LEGACY)??'{}','nihongo-odyssey-original.json');}catch{notify('瀏覽器拒絕讀取原始存檔。');}};
 $('#import').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>10_000_000)throw Error('備份檔案過大。');const incoming=restore(await f.text(),{strict:true}),s=statsSummary(incoming);if(confirm(`這份備份有 ${s.completed} 個完成詞、${s.chaptersCleared} 章新版情境。要取代目前旅程嗎？建議先下載原有備份。`)){const run=()=>{storageProblem=false;return write(incoming);};const saved=navigator.locks?await navigator.locks.request(KEY,run):run();if(saved)settingsView();}}catch(err){notify(err.message);}e.target.value='';};
}
let pendingStart=null;
document.addEventListener('click',async event=>{const b=event.target.closest('button,a[data-nav]');if(!b||b.disabled)return;const d=b.dataset;try{
 if(view==='kana'&&root.contains(b))return;
 if(d.nav){event.preventDefault();navigate(d.nav);return;}
 if(d.audio){event.preventDefault();if(d.hintAudio&&session){const active=session,token=screenToken;markHint(active);await persistEvidence(active);if(active!==session||token!==screenToken)return;}speak(d.audio,{slow:d.slow==='1',notify});return;}
 if(d.gloss){openGloss(d.gloss);return;}
 if(d.level){selectedLevel=d.level;mapView();return;}
 if(d.entryLevel){if(!leave())return;const token=screenToken;if(await mutate(s=>chooseEntryLevel(s,d.entryLevel))&&token===screenToken){selectedLevel=d.entryLevel;continueJourney();}return;}
 if(d.role){const token=screenToken,options=pendingStart;pendingStart=null;if(await mutate(s=>({...s,role:d.role}))&&token===screenToken){if(options)begin(options);else continueJourney();}return;}
 if(d.episode){if(leave())episodeView(d.episode);return;}
 if(d.choice){const token=screenToken,id=activeEpisode;if(await mutate(s=>choose(s,id,d.choice))&&token===screenToken)episodeView(id);return;}
 if(d.assessmentAnswer!==undefined){await submitAssessment(d.assessmentAnswer);return;}
 if(d.answer!==undefined){await submit(d.answer);return;}
 if(d.key){const el=$('#reading-input');el.value=d.key==='back'?[...el.value].slice(0,-1).join(''):el.value+d.key;el.focus();return;}
 if(d.word){wordView(d.word);return;}
 if(d.browseLevel){if(!leave())return;dictionaryLevel=d.browseLevel;searchTerm='';onlyLearned=false;page=0;view='lexicon';dictionaryView();return;}
 if(d.practiceLevel){if(!leave())return;const options={practice:true,level:d.practiceLevel};if(!state.role){pendingStart=options;view='roles';roleView();}else begin(options);return;}
 if(d.action){await ({continue:continueJourney,learn:()=>begin(),review:()=>begin({review:true}),'story-quiz':storyQuiz,stop:stopVoice,'save-retry':finish,ending:endingView,'close-gloss':()=>$('#gloss-dialog')?.close()}[d.action]??(()=>{}))();}
 }catch(e){notify(e.message);}});
window.addEventListener('storage',event=>{if(event.key===KEY||event.key===LEGACY){state=read();status();if((!session||session.done)&&(!assessment||assessment.done)){session=null;assessment=null;render();}}});
window.addEventListener('pagehide',stopVoice);
window.addEventListener('beforeunload',e=>{if((session&&!session.done)||(assessment&&!assessment.done)){e.preventDefault();e.returnValue='';}});
if(globalThis.speechSynthesis)speechSynthesis.addEventListener('voiceschanged',()=>{if($('#voice-status'))$('#voice-status').textContent=japaneseVoice()?`目前聲線：${japaneseVoice().name}`:'尚無可用日語聲線，文字替代不記為聽解。';});
render();

installChoiceKeyboard(document);
