import {roles,regions} from './story.js';
import {words,byId,levels,quests,chapters,counts,learnedCount,learningOrder} from './curriculum.js';
import {kanaRows,katakana} from './legacy-data.js';
import {initial,restore,currentChapter,choose,clearChapter,start,answer,commit} from './engine.js';
import {speak,stopVoice,japaneseVoice} from './voice.js';
import {readingCue,distractorPool} from './question-helpers.js';
const $=s=>document.querySelector(s),root=$('#app');
const test=new URLSearchParams(location.search).has('test');
const KEY=test?'nihongo-odyssey-test-v2':'nihongo-odyssey-v2';
let state=read(),view='map',selectedLevel='N5',session=null,learnIndex=0,activeEpisode=null,kanaType='hira',roman=true;
let searchTerm='',dictionaryLevel='all',page=0,onlyLearned=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{return restore(localStorage.getItem(KEY));}catch{return initial();}}
function notify(message){$('#notice').textContent=message;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').textContent='',7000);}
function write(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;status();return true;}catch{notify('無法儲存進度，請檢查瀏覽器是否允許網站資料。');return false;}}
function mutate(fn){const run=()=>{state=read();return write(fn(state));};return navigator.locks?navigator.locks.request(KEY,run):Promise.resolve(run());}
function status(){$('#status').textContent=`${learnedCount(state.quest).toLocaleString()} 詞 · ${state.cleared.length}/25 章`;}
function roleArt(id,extra=''){return `<div class="role-art ${extra}" role="img" aria-label="${esc(roles.find(r=>r.id===id)?.name)}的日式潑墨Q版全身像" style="--position:${roles.findIndex(r=>r.id===id)*50}%"></div>`;}
function scene(level,extra=''){const i=levels.indexOf(level);return `<div class="scene scene-${level} ${extra}" role="img" aria-label="${esc(regions[i]?.name)}潑墨風景" style="--x:${i%3*50}%;--y:${Math.floor(i/3)*100}%"></div>`;}
const fox=()=>'<div class="fox" role="img" aria-label="白狐導師白"></div>';
function audio(text,label='朗讀',slow=false){return `<button class="audio" data-audio="${esc(text)}" ${slow?'data-slow="1"':''}>${label}</button>`;}
function progress(value,max){return `<div class="progress" role="progressbar" aria-label="學習進度" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="${max}"><span style="width:${max?value/max*100:0}%"></span></div>`;}
function shell(html){root.innerHTML=html;window.scrollTo({top:0,behavior:'instant'});status();}
function leave(){if(session&&!session.done&&!confirm('這次未完成的小任務會重新開始；已完成的詞與故事會保留。要離開嗎？'))return false;session=null;stopVoice();return true;}
function navigate(next){if(!leave())return;view=next;state=read();render();}
function render(){status();({map:mapView,journal:journalView,lexicon:dictionaryView,kana:kanaView,settings:settingsView,roles:roleView}[view]??mapView)();}
function mapView(){const c=currentChapter(state),region=regions.find(r=>r.id===selectedLevel),local=chapters.filter(c=>c.level===selectedLevel),role=roles.find(r=>r.id===state.role);
 shell(`<section class="hero"><div class="hero-copy"><p class="eyebrow">日式潑墨 · 英雄之旅 · N5 → N1</p><h1>世界忘了文字，<br>你，還記得那道光。</h1><p>五座國度的言葉逐漸消失。<br>與白狐和旅人同行，把一個個詞，<br>重新寫進人們的生活。</p><div class="actions"><button class="primary" data-action="continue">${!role?'選擇旅人，啟程':c?`繼續旅程 · ${c.title}`:'重讀結局與旅途回聲'}</button><button class="ghost" data-nav="kana">從五十音暖身</button></div><small>五國 · 25 章 · ${words.length.toLocaleString()} 個參考詞條</small></div></section>
 <section class="journey-strip"><div>${role?roleArt(role.id,'mini'):fox()}</div><div><span class="eyebrow">${role?`${esc(role.name)} · ${esc(role.title)}`:'每段旅程，都需要一位同行者'}</span><p>${role?esc(c?.summary??'你把找回的文字帶回家，也替下一位旅人留下空白的一頁。'):'選擇勇於出發的空、善於傾聽的燈，或留意細節的蓮。你的視角，會留在故事裡。'}</p></div><button data-nav="roles">${role?'查看旅伴':'認識三位旅人'}</button></section>
 <section class="world"><div class="section-heading"><div><p class="eyebrow">從熟悉的問候，到理解世界的言葉</p><h2>五國旅圖</h2></div><span class="muted">已找回 ${learnedCount(state.quest).toLocaleString()} / ${words.length.toLocaleString()} 詞</span></div><div class="level-tabs" role="group" aria-label="國度與日語等級">${regions.map(r=>`<button data-level="${r.id}" class="${selectedLevel===r.id?'selected':''}"><strong>${r.id}</strong>${esc(r.name)}<small>${counts[r.id].toLocaleString()} 詞</small></button>`).join('')}</div>
 <div class="realm-panel">${scene(selectedLevel)}<div><p class="eyebrow">${region.id} · ${esc(region.subtitle)}</p><h2>${esc(region.name)}</h2><p>${esc(region.description)}</p><button data-browse-level="${selectedLevel}">先翻閱這一國的詞彙</button></div></div>
 <div class="chapter-list">${local.map((e,i)=>{const unlocked=chapters.indexOf(e)<=state.cleared.length,done=state.cleared.includes(e.id),count=Math.max(0,Math.min(e.end-e.start,state.quest-e.start));return `<button class="chapter ${done?'completed':unlocked?'current':''}" data-episode="${e.id}"><span class="chapter-number">${String(i+1).padStart(2,'0')}</span><span><small>${esc(e.beat)}</small><strong>${esc(e.title)}</strong><small>${e.wordCount} 詞 · ${e.end-e.start} 個小任務</small></span><span class="chapter-state">${done?'已得印記':unlocked?`${count}/${e.end-e.start} · 進入`:'劇情預覽'}</span></button>`;}).join('')}</div></section>`);
}
function roleView(){shell(`<section class="page-title"><p class="eyebrow">同一條路，三種看見世界的方式</p><h1>誰，將替這個世界寫下下一頁？</h1><p>角色會帶來不同的觀察與故事回應。選擇沒有對錯，旅途中也能更換。</p></section><section class="role-grid">${roles.map(r=>`<article class="role-card ${state.role===r.id?'selected':''}">${roleArt(r.id)}<div class="role-copy"><p class="eyebrow">${esc(r.title)}</p><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><p class="trait">${esc(r.trait)}</p><button class="primary" data-role="${r.id}">${state.role===r.id?'繼續同行':'與我同行'}</button></div></article>`).join('')}</section><div class="mentor">${fox()}<p>白：「不是最勇敢的人才能出發。<br>願意說出第一句話的人，就已經在路上了。」</p></div>`);}
function episodeView(id){const e=chapters.find(c=>c.id===id);if(!e)return;activeEpisode=id;const idx=chapters.indexOf(e),unlocked=idx<=state.cleared.length,done=state.cleared.includes(id),choice=e.choices.find(x=>x.id===state.choices[id]),role=roles.find(r=>r.id===state.role),previous=chapters[idx-1],echo=previous?.choices.find(x=>x.id===state.choices[previous.id]);
 shell(`<section class="story-layout"><aside class="story-aside">${scene(e.level)}<div class="story-guide">${role?roleArt(role.id,'small'):fox()}<div><p class="eyebrow">${esc(role?.name??'白')}的視角</p><p>${esc(e.roleNotes[state.role]??e.summary)}</p></div></div><button data-nav="map">返回旅圖</button></aside><article class="story-paper"><p class="eyebrow">${e.level} · ${esc(e.beat)} · 第 ${idx+1} / 25 章</p><h1>${esc(e.title)}</h1>${!unlocked?'<p class="tip">這是故事預覽。主線會依序抵達這裡；想先學這一級，可前往言葉辭典。</p>':''}${echo?`<blockquote><small>前一段旅途的回聲</small><p>${esc(echo.echo)}</p></blockquote>`:''}<div class="audio-bar">${audio(e.paragraphs.map(p=>p.ja).join('\n'),'聽完整日文故事')}${audio(e.paragraphs.map(p=>p.ja).join('\n'),'慢速',true)}<button data-action="stop">停止</button><button id="translation-toggle">隱藏中文</button></div><div class="story-text">${e.paragraphs.map(p=>`<div class="paragraph"><p lang="ja">${esc(p.ja)}</p><p class="translation">${esc(p.zh)}</p></div>`).join('')}</div><div class="dialogue">${fox()}<div>${e.dialogue.map(d=>`<p><strong>${esc(roles.find(r=>r.id===d.speaker)?.name??'白')}：</strong><span lang="ja">${esc(d.ja)}</span></p><p class="translation">${esc(d.zh)}</p>${audio(d.ja,'聽對話')}`).join('')}</div></div>
 <section class="decision"><p class="eyebrow">你的抉擇，會在下一章留下回聲</p>${choice?`<h3>${esc(choice.label)}</h3><p>${esc(choice.result)}</p>`:`<h3>你想怎麼做？</h3><div class="choices">${e.choices.map(o=>`<button data-choice="${o.id}" ${!unlocked||!role?'disabled':''}>${esc(o.label)}</button>`).join('')}</div>${!role?'<button data-nav="roles">先選擇你的旅人</button>':''}`}</section>
 <section class="chapter-mission"><h3>找回本章的 ${e.wordCount} 個言葉</h3><p>每次最多五個新詞。先閱讀、練習辨義與讀音，再把詞放回記憶裡。</p>${progress(Math.max(0,Math.min(e.end-e.start,state.quest-e.start)),e.end-e.start)}<small>${Math.max(0,Math.min(e.end-e.start,state.quest-e.start))} / ${e.end-e.start} 個小任務</small><div class="actions">${!done&&unlocked&&choice?`<button class="primary" data-action="${state.quest>=e.end?'story-quiz':'learn'}">${state.quest>=e.end?'完成章節閱讀考驗':'出發 · 找回五個詞'}</button>`:''}<button data-browse-level="${e.level}">翻閱 ${e.level} 詞彙</button>${done?`<span class="reward">✓ ${esc(e.reward)}</span>`:''}</div></section></article></section>`);
 $('#translation-toggle').onclick=()=>{root.classList.toggle('hide-translations');$('#translation-toggle').textContent=root.classList.contains('hide-translations')?'顯示中文':'隱藏中文';};
}
function continueJourney(){if(!state.role){view='roles';roleView();return;}const c=currentChapter(state);if(c){selectedLevel=c.level;episodeView(c.id);}else endingView();}
function storyQuiz(){const e=currentChapter(state);if(!e||state.quest<e.end)return;activeEpisode=e.id;shell(`<section class="panel"><p class="eyebrow">${esc(e.title)} · 閱讀考驗</p><h1>帶著理解，通過這一道門。</h1><p>${esc(e.question.prompt)}</p><div class="choices">${e.question.options.map((o,i)=>`<button data-story-answer="${i}">${esc(o)}</button>`).join('')}</div><p class="feedback" id="story-feedback" role="status"></p><button data-episode="${e.id}">回顧本章故事</button></section>`);}
function begin(review=false){try{state=read();session=start(state,{review,listening:!!japaneseVoice()});if(!session.queue.length){notify('先完成一個小任務，再回來複習。');session=null;return;}learnIndex=0;stopVoice();session.fresh.length?learnView():questionView();}catch(e){notify(e.message);continueJourney();}}
function learnView(){const w=session.fresh[learnIndex],e=currentChapter(state);shell(`<section class="lesson-layout"><aside class="lesson-guide">${roleArt(state.role,'lesson-role')}<p class="eyebrow">${esc(e?.title??'旅途複習')}</p><h2>找回失落的言葉</h2><p>${esc(e?.roleNotes[state.role]??'熟悉的詞，再次相見。')}</p><small>本次 ${session.fresh.length} 詞 · 全站 ${words.length.toLocaleString()} 詞</small><button data-nav="map">返回旅圖</button></aside><article class="word-paper"><p class="eyebrow">${w.level} · 新詞 ${learnIndex+1} / ${session.fresh.length}</p>${progress(learnIndex+1,session.fresh.length)}<h1 lang="ja" class="word">${esc(w.word)}</h1><p lang="ja" class="reading">${esc(w.kana)}</p><p class="meaning">${esc(w.meaning)}</p><div class="audio-bar">${audio(w.kana,'聽讀音')}${audio(w.kana,'慢速',true)}<button data-action="stop">停止</button></div>${w.example?`<div class="example"><p lang="ja">${esc(w.example)}</p><p>${esc(w.translation)}</p>${audio(w.example,'聽例句')}</div>`:'<p class="muted">本詞來源未提供完整例句；先認識詞義與讀音。</p>'}<div class="actions"><button class="primary" id="learn-next">${learnIndex===session.fresh.length-1?'開始旅途練習':'下一個詞'}</button></div></article></section>`);$('#learn-next').onclick=()=>{stopVoice();++learnIndex<session.fresh.length?learnView():questionView();};}
function shuffled(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function questionView(){const q=session.queue[0];if(!q){finish();return;}const w=byId.get(q.id),reading=q.mode==='reading',listen=q.mode==='listening';let distractors=shuffled(distractorPool(w,words)).slice(0,30);const meanings=shuffled([w.meaning,...[...new Set(distractors.map(x=>x.meaning))].slice(0,3)]);
 shell(`<section class="panel quiz"><p class="eyebrow">${q.review?'旅途複習':'言葉試煉'} · 還有 ${session.queue.length} 題</p><h1>${reading?'讓記憶，化成一句日語。':listen?'聽見了什麼言葉？':'這個言葉，帶著什麼意思？'}</h1><p class="muted">${reading?'輸入假名。平假名、片假名皆可；不接受羅馬拼音。':listen?'先按播放，聽完再選出意思。':'讀一讀，再選出意思。'}</p><div class="quiz-word">${reading?`<p class="meaning">${esc(w.meaning)}</p>${readingCue(w,words)?`<p class="reading" lang="ja">本題指定：${esc(w.word)}</p>`:''}`:listen?`<div class="listen-symbol">音</div>${audio(w.kana,'播放日語')}${audio(w.kana,'慢速',true)}<button id="text-mode">改用文字題</button>`:`<p lang="ja" class="word">${esc(w.word)}</p><p lang="ja" class="reading">${esc(w.kana)}</p>`}</div>${reading?`<form id="reading-form"><label for="reading-input">日文假名</label><input id="reading-input" autocomplete="off" lang="ja" required><div class="actions"><button class="primary" type="submit">確認答案</button><button type="button" id="hint">需要提示</button>${audio(w.kana,'聽提示')}</div><p id="hint-text" class="muted"></p><details class="kana-keyboard"><summary>沒有日文鍵盤？展開假名小鍵盤</summary><div>${[...'あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをんがぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽゃゅょっぁぃぅぇぉー'].map(k=>`<button type="button" data-key="${k}">${k}</button>`).join('')}<button type="button" data-key="back">退一字</button></div></details></form>`:`<div class="choices">${meanings.map(m=>`<button data-answer="${esc(m)}">${esc(m)}</button>`).join('')}</div>`}<p id="feedback" class="feedback" role="status"></p><button class="primary" id="next" hidden>繼續</button><button class="quiet" data-nav="map">回旅圖</button></section>`);
 if(reading){$('#reading-form').onsubmit=e=>{e.preventDefault();submit($('#reading-input').value);};$('#hint').onclick=()=>$('#hint-text').textContent=`跟著讀一次：${w.kana}`;}
 if(listen)$('#text-mode').onclick=()=>{q.mode='meaning';stopVoice();questionView();};
 $('#next').onclick=()=>{stopVoice();session.done?finish():questionView();};
}
function submit(value){const r=answer(session,value);if(!r)return;root.querySelectorAll('.choices button,form button,form input').forEach(el=>el.disabled=true);$('#feedback').className=`feedback ${r.ok?'':'wrong'}`;$('#feedback').textContent=r.ok?'答對了。這個言葉，又亮了一點。':`這一題是「${r.expected}」。別急，稍後再遇見它一次。`;$('#next').hidden=false;$('#next').focus();}
async function finish(){const completed=session;const saved=await mutate(s=>commit(s,completed));const c=currentChapter(state),end=c&&state.quest>=c.end;shell(`<section class="panel achievement">${fox()}<p class="eyebrow">${saved?'旅程已保存':'儲存未成功，請留在本頁重試'}</p><h1>微小的言葉，也能點亮一條路。</h1><p>找回 ${completed.fresh.length} 個新詞，複習 ${completed.reviewed.length} 詞。<br>這次重試 ${completed.retries} 次；願意再試，本身就是勇氣。</p><p>${esc(c?.choices.find(x=>x.id===state.choices[c.id])?.result??'你聽見熟悉的聲音，重新在風裡響起。')}</p><div class="actions"><button class="primary" data-action="${saved?(end?'story-quiz':completed.fresh.length?'learn':'review'):'save-retry'}">${saved?(end?'迎向章節考驗':completed.fresh.length?'再找回五個詞':'再複習一組'):'重試儲存'}</button><button data-nav="map">回旅圖休息</button></div></section>`);}
function dictionaryView(){const learned=new Set(learningOrder.slice(0,learnedCount(state.quest)).map(w=>w.id));const query=searchTerm.trim().toLocaleLowerCase();const matches=words.filter(w=>(dictionaryLevel==='all'||w.level===dictionaryLevel)&&(!onlyLearned||learned.has(w.id))&&(!query||[w.word,w.kana,w.meaning].some(v=>v.toLocaleLowerCase().includes(query))));const pages=Math.max(1,Math.ceil(matches.length/24));page=Math.min(page,pages-1);const shown=matches.slice(page*24,page*24+24);
 shell(`<section class="page-title"><p class="eyebrow">把沿途的言葉，收進自己的行囊</p><h1>言葉辭典</h1><p>可以自由翻閱各級詞彙；瀏覽辭典不會計入闖關進度。</p></section><form id="search-form" class="search-bar"><label for="search">日文、假名或中文</label><input id="search" value="${esc(searchTerm)}" placeholder="例如：ありがとう、感謝"><label for="filter">等級</label><select id="filter"><option value="all">全部等級</option>${levels.map(l=>`<option ${dictionaryLevel===l?'selected':''}>${l}</option>`).join('')}</select><button class="primary">搜尋</button><label class="check"><input id="only-learned" type="checkbox" ${onlyLearned?'checked':''}>只看已學詞</label></form><div class="section-heading"><p>找到 ${matches.length.toLocaleString()} 詞 · 第 ${page+1} / ${pages} 頁</p><button data-action="review" ${state.quest?'':'disabled'}>複習已學詞</button></div><div class="dictionary-grid">${shown.map(w=>`<article class="dictionary-card"><span class="badge">${w.level}${learned.has(w.id)?' · 已學':''}</span><h2 lang="ja">${esc(w.word)}</h2><p lang="ja">${esc(w.kana)}</p><p>${esc(w.meaning)}</p><div class="audio-bar">${audio(w.kana,'聽讀音')}<button data-word="${w.id}">例句與詳情</button></div></article>`).join('')||'<p class="empty">沒有符合的詞，換個關鍵字試試。</p>'}</div><div class="pagination"><button id="prev-page" ${page===0?'disabled':''}>上一頁</button><span>${page+1} / ${pages}</span><button id="next-page" ${page>=pages-1?'disabled':''}>下一頁</button></div>`);
 $('#search-form').onsubmit=e=>{e.preventDefault();searchTerm=$('#search').value;dictionaryLevel=$('#filter').value;onlyLearned=$('#only-learned').checked;page=0;dictionaryView();};$('#filter').onchange=()=>$('#search-form').requestSubmit();$('#only-learned').onchange=()=>$('#search-form').requestSubmit();$('#prev-page').onclick=()=>{page--;dictionaryView();};$('#next-page').onclick=()=>{page++;dictionaryView();};
}
function wordView(id){const w=byId.get(id);if(!w)return;shell(`<article class="panel word-detail"><span class="badge">${w.level}</span><h1 class="word" lang="ja">${esc(w.word)}</h1><p lang="ja" class="reading">${esc(w.kana)}</p><p class="meaning">${esc(w.meaning)}</p><div class="audio-bar">${audio(w.kana,'聽讀音')}${audio(w.kana,'慢速',true)}<button data-action="stop">停止</button></div>${w.example?`<div class="example"><p lang="ja">${esc(w.example)}</p><p>${esc(w.translation)}</p>${audio(w.example,'聽完整例句')}</div>`:'<p>來源未提供完整例句。</p>'}<small class="muted">來源：egg rolls · 社群分級 ${esc((w.sourceLevels??[w.level]).join('／'))}</small><div class="actions"><button data-nav="lexicon">回言葉辭典</button></div></article>`);}
function journalView(){shell(`<section class="page-title"><p class="eyebrow">抉擇不是消失了，它正在別處發芽</p><h1>故事手札</h1><p>已完成 ${state.cleared.length} / 25 章。每一枚印記，都有一段你走過的故事。</p></section><div class="journal-grid">${chapters.filter(c=>state.choices[c.id]).map(c=>{const choice=c.choices.find(o=>o.id===state.choices[c.id]);return `<article class="journal-card"><p class="eyebrow">${c.level} · ${esc(c.beat)}</p><h2>${esc(c.title)}</h2><strong>${esc(choice.label)}</strong><p>${esc(choice.result)}</p><blockquote>${esc(choice.echo)}</blockquote><span class="reward">${state.cleared.includes(c.id)?`✓ ${esc(c.reward)}`:'旅途進行中'}</span><button data-episode="${c.id}">重讀這一章</button></article>`;}).join('')||`<div class="panel">${fox()}<p>手札的第一頁還是空白。帶上你的旅人，寫下第一個決定。</p><button class="primary" data-action="continue">寫下序章</button></div>`}</div>${state.cleared.length===25?'<button class="primary" data-action="ending">閱讀你的返鄉結局</button>':''}`);}
function endingView(){if(state.cleared.length<25){journalView();return;}shell(`<section class="ending"><div class="ending-copy"><p class="eyebrow">英雄之旅 · 帶著禮物歸返</p><h1>你找回的，<br>不只是一萬個言葉。</h1><p>空白的卷軸終於有了聲音。<br>而最重要的一頁，是你願意留給下一個人的那一頁。</p><p>五國旅程完成 · ${words.length.toLocaleString()} 詞 · 25 章</p></div></section><section class="panel"><h2>你的選擇，回到了家</h2>${chapters.map(c=>{const o=c.choices.find(x=>x.id===state.choices[c.id]);return `<div class="ending-echo"><h3>${esc(c.title)} · ${esc(c.reward)}</h3><p>${esc(o?.ending)}</p></div>`;}).join('')}<div class="actions"><button data-nav="journal">重讀全部抉擇</button><button class="primary" data-action="review">讓言葉留在心裡 · 複習</button></div></section>`);}
function kanaView(){shell(`<section class="panel"><p class="eyebrow">旅程的第一道聲音</p><h1>從五十音，慢慢開始。</h1><p>點一格聽讀音。先熟悉五個母音，再一行一行往下走；已經會了，可以直接出發。</p><div class="tabs"><button data-kana-type="hira" class="${kanaType==='hira'?'selected':''}">平假名</button><button data-kana-type="kata" class="${kanaType==='kata'?'selected':''}">片假名</button><button id="toggle-roman">${roman?'隱藏':'顯示'}拼音</button></div><div class="kana-grid">${kanaRows.map(([row,rom])=>[...row].map((k,i)=>k==='　'?'<span></span>':`<button data-audio="${kanaType==='hira'?k:katakana(k)}"><span lang="ja">${kanaType==='hira'?k:katakana(k)}</span>${roman?`<small>${rom.split(' ')[i]}</small>`:''}</button>`).join('')).join('')}</div><div class="tip"><p>促音「っ」：下一個子音停一下，例如 きっぷ（車票）。</p><p>拗音「きゃ／きゅ／きょ」合成一拍；長音「ー」拉長前面的母音，例如 コーヒー。</p><p>助詞「は」讀 wa、「へ」讀 e、「を」讀 o；「ん」是一拍。</p></div><div class="actions"><button class="primary" id="kana-practice">開始五題辨讀</button><button data-action="continue">前往故事主線</button></div></section>`);$('#toggle-roman').onclick=()=>{roman=!roman;kanaView();};$('#kana-practice').onclick=()=>kanaPractice(0);}
function kanaPractice(n){const items=[['あ','a'],['し','shi'],['つ','tsu'],['ね','ne'],['ん','n']];if(n>=items.length){mutate(s=>({...s,kanaDone:true}));shell(`<section class="panel achievement">${fox()}<h1>第一道聲音，已經響起。</h1><p>五題暖身完成。你可以反覆回來練習，也可以出發認識旅伴。</p><button class="primary" data-action="continue">開始故事旅程</button></section>`);return;}const [k,rom]=items[n];shell(`<section class="panel quiz"><p class="eyebrow">五十音暖身 ${n+1}/5</p><h1>這個假名怎麼讀？</h1><p class="word" lang="ja">${kanaType==='hira'?k:katakana(k)}</p>${audio(k,'聽讀音')}<div class="choices">${shuffled([rom,'ka','mi','yo']).map(r=>`<button data-rom-answer="${r}">${r}</button>`).join('')}</div><p class="feedback" id="kana-feedback" role="status"></p><button class="primary" id="kana-next" hidden>下一題</button></section>`);root.querySelectorAll('[data-rom-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.romAnswer===rom;$('#kana-feedback').textContent=ok?'答對了！':`讀作 ${rom}，再試一次。`;if(ok){root.querySelectorAll('[data-rom-answer]').forEach(x=>x.disabled=true);$('#kana-next').hidden=false;}});$('#kana-next').onclick=()=>kanaPractice(n+1);}
function settingsView(){let legacy=false;try{legacy=!!localStorage.getItem(test?'nihongo-odyssey-test-v1':'nihongo-odyssey-v1');}catch{}shell(`<section class="panel"><p class="eyebrow">讓這段旅程，安心留在身邊</p><h1>旅程設定與備份</h1><h2>你的旅程</h2><p>已學 ${learnedCount(state.quest).toLocaleString()} 詞 · 完成 ${state.quest}/${quests.length} 個小任務 · ${state.cleared.length}/25 章。</p><p>進度僅存在這個瀏覽器，尚未提供登入與跨裝置同步。</p>${legacy?'<p class="tip">舊版十站、100 詞的存檔仍保留。新版五國課程另存，不把舊版完成數誤當成新版詞庫進度。</p>':''}<div class="actions"><button class="primary" id="export">下載旅程備份</button><label class="file-button">匯入旅程備份<input id="import" type="file" accept="application/json,.json"></label></div><h2>日語朗讀</h2><p id="voice-status">${japaneseVoice()?`目前聲線：${esc(japaneseVoice().name)}`:'尚未偵測到日語聲線。請先在裝置語音設定安裝日語；仍可完整使用文字練習。'}</p><div class="audio-bar">${audio('こんにちは。ことばをさがすたびにでましょう。','試聽日語')}${audio('こんにちは。ことばをさがすたびにでましょう。','慢速',true)}<button data-action="stop">停止</button></div><p>所有詞條、來源提供的例句、故事日文段落與對話皆可朗讀。裝置是否需要網路取決於聲線；本站未內建錄製音檔。</p><h2>關於詞彙與故事</h2><p>原始資料 10,641 筆，去重後 ${words.length.toLocaleString()} 詞。122 詞來源沒有完整例句，頁面會如實標示。全詞庫可查詢與練習；分級並非官方考試清單，也不等於完整的 JLPT 應考課程。</p><p>英雄之旅包含 25 篇原創故事、三位旅人、五座國度。五幅國度插圖沿章節共用；故事難度漸進，但尚未經逐篇日語教學校訂。</p><a href="THIRD-PARTY-NOTICES.md" target="_blank">查看完整來源與授權</a></section>`);$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(read(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nihongo-odyssey-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('#import').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>5_000_000)throw Error('備份檔案過大。');const incoming=restore(await f.text(),{strict:true});if(confirm(`這份備份有 ${learnedCount(incoming.quest)} 個已學詞、${incoming.cleared.length} 章。要取代目前旅程嗎？建議先下載原有備份。`)){if(await mutate(()=>incoming))settingsView();}}catch(err){notify(err.message);}e.target.value='';};}
document.addEventListener('click',async event=>{const b=event.target.closest('button,a[data-nav]');if(!b||b.disabled)return;const d=b.dataset;try{
 if(d.nav){event.preventDefault();navigate(d.nav);return;}
 if(d.audio){event.preventDefault();speak(d.audio,{slow:d.slow==='1',notify});return;}
 if(d.level){selectedLevel=d.level;mapView();return;}
 if(d.role){if(await mutate(s=>({...s,role:d.role})))continueJourney();return;}
 if(d.episode){if(leave())episodeView(d.episode);return;}
 if(d.choice){if(await mutate(s=>choose(s,activeEpisode,d.choice)))episodeView(activeEpisode);return;}
 if(d.storyAnswer!==undefined){let result;const saved=await mutate(s=>{result=clearChapter(s,d.storyAnswer,activeEpisode);return result.state;});if(!saved)return;if(!result.ok){$('#story-feedback').textContent=`再想一想：${chapters.find(c=>c.id===activeEpisode).question.explanation}`;return;}const e=chapters.find(c=>c.id===activeEpisode);shell(`<section class="panel achievement">${fox()}<p class="eyebrow">章節考驗完成</p><h1>你取得了「${esc(e.reward)}」</h1><p>${esc(e.question.explanation)}</p><p>${esc(e.choices.find(x=>x.id===state.choices[e.id]).ending)}</p><div class="actions"><button class="primary" data-action="continue">${state.cleared.length===25?'帶著言葉返鄉':'走向下一章'}</button><button data-nav="journal">收進故事手札</button></div></section>`);return;}
 if(d.answer!==undefined){submit(d.answer);return;}
 if(d.key){const el=$('#reading-input');el.value=d.key==='back'?[...el.value].slice(0,-1).join(''):el.value+d.key;el.focus();return;}
 if(d.word){wordView(d.word);return;}
 if(d.browseLevel){if(!leave())return;dictionaryLevel=d.browseLevel;searchTerm='';onlyLearned=false;page=0;view='lexicon';dictionaryView();return;}
 if(d.kanaType){kanaType=d.kanaType;kanaView();return;}
 if(d.action){({continue:continueJourney,learn:()=>begin(false),review:()=>begin(true),'story-quiz':storyQuiz,stop:stopVoice,'save-retry':finish,ending:endingView}[d.action]??(()=>{}))();}
 }catch(e){notify(e.message);}});
window.addEventListener('storage',event=>{if(event.key===KEY){state=read();status();if(!session||session.done){session=null;render();}}});
window.addEventListener('pagehide',stopVoice);
window.addEventListener('beforeunload',e=>{if(session&&!session.done){e.preventDefault();e.returnValue='';}});
if(globalThis.speechSynthesis)speechSynthesis.addEventListener('voiceschanged',()=>{if($('#voice-status'))$('#voice-status').textContent=japaneseVoice()?`目前聲線：${japaneseVoice().name}`:'尚無可用日語聲線。';});
render();
